org: aleynaalangil
app: serverlessecr
service: serverlessecr
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct


functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
plugins:
  - serverless-plugin-typescript
package:
  excludeDevDependencies: true
  individually: true
